### ISSUE TITLE
Not shutting down Meteor in Windows Preview 0.1.7 (Feb 9, 2015)

### ISSUE THREAD

**Issue by landmaxcanada** [PEM--/meteor-helper#25]
Using Atom.io on Windows 7, it seems that the meteor starts fine but does not stop when "Toggle" is selected.

**Comment by PEM--** [comment]
Meteor on Windows? Ho ho, things are getting serious :wink: 

Indeed, it can't. I'm using a UNIX / BSD command for killing the process: `killall`. I was having trouble stopping the Mongo instance on some cases.

I'm keeping the issue opened until Meteor is officially supported on Windows. I will check if I can do something about it. It will all depend on the way Meteor will spawn Mongo in their official release.

Thanks for the report.

**Comment by tbiggins** [comment]
Can I (sadly) ask what I should have as the Meteor Path ("customize Meteor's launching command") value for Windows?  
I'm running a project in c:\temp\Meteor\project1 folder.
My environment path is: C:\Users\<my account>\AppData\Local\.meteor
I tried:
C:\Users\<my account>\AppData\Local\.meteor\   -and-
C:\Users\<my account>\AppData\Local\.meteor\meteor
and I'm waiting for the obvious 'duh' moment... ;-)

**Comment by PEM--** [comment]
JS considers the `\` as an escaping character. For win32 using a double `\\` stance should allow you to setup paths properly:
```
c:\\Users\\<my account>\\AppData\\Local.meteor\\meteor
```

**Comment by PEM--** [comment]
Hum... Seems like putting Meteor into a batch file removes the capability of Node to access some required system command.

**Comment by tbiggins** [comment]
Cool - I figured out a work-around but it's a bit silly:
`C:\Users\(user location)\AppData\Local\.meteor\meteor.bat
uses SETLOCAL to set meteor variables
But when you run this in a Windows command shell, it's pulling the normal SET variables including PATH (which is required to point to the system32 folder for tasklist.exe)

So... 
1. duplicate the meteor.bat file - call the new copy "atommeteor.bat"
2. open a command prompt, type "SET", then hit ENTER. Copy the PATH variable and paste it into the new atommetor.bat file, just under the SETLOCAL line.  But instead of "PATH=", put "SET PATH="  - and remember to fix the line wrapping, because Windows likes to line return a lot.
3. create a launcher in the folder for your project - call it launcher.cmd. This file has one line:
`C:\Users\(user folder)\AppData\Local\.meteor\atommeteor.bat

I know - it's silly - but ... that's the best I could do. ha ha  Removing any of these steps seems to break dependencies.

Thanks again!!

**Comment by PEM--** [comment]
Happy that it works for you and thanks for your feedback.
By any chance, could you check if your move fixes @landmaxcanada's issue?

**Comment by tbiggins** [comment]
Ha ha - I'm so new to Meteor AND Atom ... I didn't realize my issue was exactly what he was reporting; I didn't know what Toggle was, I just wanted to start Meteor. ha ha

Packages>Meteor>Toggle is in fact Alt + CTRL+ M, which is what I was using to make it work.  So yes this solves his problem.  But I'm open to any improvements over my hack. ;-)

**Comment by PEM--** [comment]
First time user. Wow. Super nice move. Your trick is making the Mongo execution into the same process as the Node's one. Thus making the UNIX/BSD `killall` unecessary on Windows. :clap:

**Comment by tbiggins** [comment]
Even a broken clock is correct twice a day.  I get lucky sometimes.  Thanks so much for your work!
