### ISSUE TITLE
Closing Atom won't shutdown meteor

### ISSUE THREAD

**Issue by zimme** [PEM--/meteor-helper#3]
When closing Atom the meter/mongodb processes keeps running in background.
Starting Atom again and toggling meteor-helper it tries to start a new meteor process
with results in error because of already running meteor server.

**Comment by elGatoMantocko** [comment]
@PEM-- can we reopen this issue? It doesn't appear to work on Windows.

**Comment by PEM--** [comment]
Humm, different problem and root cause. The case is specific to Windows. When killing process, I use a `killall` command to Mongo in case it hasn't been stopped. This additional measure can't work on Windows as this shell command doesn't exist on this system. Windows users have reported that by creating a shell script could help (see the end of the README).
